In [1]:
import numpy as np
import pandas as pd

In [2]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Replace all the elements in the third column with 1
array[:, 2] = 1
print("Modified array:")
print(array)

Original array:
[[16  9  6  1  1]
 [20 11 12 17  4]
 [19 12 19 11 11]
 [ 3  9  6 18  8]
 [11 18  7  1 12]]
Modified array:
[[16  9  1  1  1]
 [20 11  1 17  4]
 [19 12  1 11 11]
 [ 3  9  1 18  8]
 [11 18  1  1 12]]


In [27]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
array = np.random.randint(1, 17, size=(4, 4))
print("Original array:")
print(array)

np.fill_diagonal(array, 0)
print("Modified array:")  
print(array)


Original array:
[[ 7  5  3 13]
 [ 1 10  2  2]
 [15 13 11  8]
 [14 10  9 16]]
Modified array:
[[ 0  5  3 13]
 [ 1  0  2  2]
 [15 13  0  8]
 [14 10  9  0]]


In [31]:
# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
array = np.random.randint(1, 37, size=(6, 6))
print("Original array:")
print(array)


sub_arr1 = array[2:5, 1:4]
print("Extracted sub-array:")
print(sub_arr1)

# 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

array2 = np.random.randint(1, 26, size=(5, 5))
print("Original array:")
print(array2)

border_elements = np.concatenate((array2[0, :], array2[-1, :], array2[1:-1, 0], array2[1:-1, -1]))
print("Border elements:")
print(border_elements)

Original array:
[[ 9  7 31  2 27 13]
 [27  4  8 36 30  3]
 [31  4  6 21 28 22]
 [29  5 25 33 32 17]
 [36  6 24 17 26 19]
 [29 22  8 18 12 14]]
Extracted sub-array:
[[ 4  6 21]
 [ 5 25 33]
 [ 6 24 17]]
Original array:
[[ 8  5  2 25  8]
 [13  3 25 20  4]
 [ 7 19 14  5  7]
 [ 2  9 16 25 17]
 [21 11  1  7 18]]
Border elements:
[ 8  5  2 25  8 21 11  1  7 18 13  7  2  4  7 17]


In [33]:
# 1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.
# Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers
df = pd.DataFrame(np.random.randint(1, 100, size=(6, 4)), columns=['A', 'B', 'C', 'D'])
print("Original DataFrame:")
print(df)

# Set the index to be the first column
df.set_index('A', inplace=True)
print("DataFrame with new index:")
print(df)

# 2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

df2 = pd.DataFrame(np.random.randint(1, 100, size=(3, 3)), columns=['A', 'B', 'C'], index=['X', 'Y', 'Z'])
print("DataFrame:")
print(df2)
print("Element at row 'Y' and column 'B':")
print(df2.loc['Y', 'B'])

Original DataFrame:
    A   B   C   D
0  30  87  41  13
1  76  24  37  14
2  90  10  66   8
3  45  87  84  59
4  13  50  51  34
5  38  46  95  78
DataFrame with new index:
     B   C   D
A             
30  87  41  13
76  24  37  14
90  10  66   8
45  87  84  59
13  50  51  34
38  46  95  78
DataFrame:
    A   B   C
X  19  49  40
Y  75  68  27
Z  27  62  95
Element at row 'Y' and column 'B':
68


In [36]:
# 1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.

df = pd.DataFrame(np.random.randint(1, 100, size=(5, 3)), columns=['A', 'B', 'C'])
print("Original DataFrame:") 
print(df)

df['D'] = df['A'] * df['B']
print("DataFrame with new column 'D':")
print(df)

# 2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.
df2 = pd.DataFrame(np.random.randint(1, 100, size=(4, 3)), columns=['A', 'B', 'C'])
print("Original DataFrame:") 
print(df2)

row_sum = df2.sum(axis=1)
col_sum = df2.sum(axis=0)
print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(col_sum)



Original DataFrame:
    A   B   C
0  12  58  78
1  63  88  71
2  11  67  76
3   6  81  99
4  23  12  72
DataFrame with new column 'D':
    A   B   C     D
0  12  58  78   696
1  63  88  71  5544
2  11  67  76   737
3   6  81  99   486
4  23  12  72   276
Original DataFrame:
    A   B   C
0  57  60  19
1  20  74   2
2   1  40  96
3  80  86   2
Row-wise sum:
0    136
1     96
2    137
3    168
dtype: int64
Column-wise sum:
A    158
B    260
C    119
dtype: int64


In [ ]:
# 1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.

df = pd.DataFrame(np.random.randint(1, 100, size=(5, 3)), columns=['A', 'B', 'C'])
print("Original DataFrame:") 
print(df)

df.loc[1, 'A'] = np.nan
df.loc[3, 'B'] = np.nan
df.loc[4, 'C'] = np.nan
  
print("DataFrame with NaN values:") 
print(df)

# Fill NaN values with the mean of the respective columns
df = df.fillna(df.mean())

print("DataFrame after filling NaN values:") 
print(df)


Original DataFrame:
    A   B   C
0  55  80  54
1  84  85   2
2  48  98  62
3  74  17  35
4  76  98  40
DataFrame with NaN values:
      A     B     C
0  55.0  80.0  54.0
1   NaN  85.0   2.0
2  48.0  98.0  62.0
3  74.0   NaN  35.0
4  76.0  98.0   NaN
DataFrame after filling NaN values:
       A      B      C
0  55.00  80.00  54.00
1  63.25  85.00   2.00
2  48.00  98.00  62.00
3  74.00  90.25  35.00
4  76.00  98.00  38.25


In [44]:
# 2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

df2 = pd.DataFrame(np.random.randint(1, 100, size=(6, 4)), columns=['A', 'B', 'C', 'D'])
print("Original DataFrame:")  
print(df2)

# Introduce some NaN values
df2.loc[1, 'A'] = np.nan
df2.loc[3, 'B'] = np.nan
df2.loc[4, 'C'] = np.nan
df2.loc[5, 'D'] = np.nan
print("DataFrame with NaN values:")
print(df2)

# Drop rows with any NaN values
df2 = df2.dropna()
print("DataFrame after dropping rows with NaN values:")
print(df2)

Original DataFrame:
    A   B   C   D
0  73  58  96  11
1  32  17  72  34
2  61  35  69  26
3  56  17  65  12
4  43  79  76   5
5  69   7  42  75
DataFrame with NaN values:
      A     B     C     D
0  73.0  58.0  96.0  11.0
1   NaN  17.0  72.0  34.0
2  61.0  35.0  69.0  26.0
3  56.0   NaN  65.0  12.0
4  43.0  79.0   NaN   5.0
5  69.0   7.0  42.0   NaN
DataFrame after dropping rows with NaN values:
      A     B     C     D
0  73.0  58.0  96.0  11.0
2  61.0  35.0  69.0  26.0
