In [172]:
import numpy as np


In [173]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [174]:
a = [1,2,3.5]
np.array(a)

array([1. , 2. , 3.5])

In [175]:
lst = [[1,2,3],[4,5,6],[7,8,9]]
np.array(lst)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [176]:
# array generaration
arr = np.arange(1,11,1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [177]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [178]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [179]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [180]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [181]:
# normalizatin value ranges from 0 to 1
np.random.rand(50)

array([0.34532137, 0.09233931, 0.40407902, 0.25869722, 0.76394036,
       0.91612525, 0.31206351, 0.15929749, 0.21423701, 0.62812614,
       0.68805974, 0.68149695, 0.64516662, 0.58713733, 0.64503501,
       0.44455589, 0.20364579, 0.13555338, 0.02177088, 0.39685095,
       0.17674266, 0.20052612, 0.81693041, 0.86980589, 0.48364702,
       0.31747179, 0.51655307, 0.72715967, 0.86326361, 0.66400006,
       0.23263492, 0.73255474, 0.75147646, 0.08622551, 0.94370992,
       0.87043883, 0.94430003, 0.09223684, 0.13067103, 0.05274854,
       0.03841906, 0.89497241, 0.32576903, 0.21645632, 0.17121605,
       0.26470601, 0.62214053, 0.92038303, 0.49512204, 0.20019714])

In [182]:
# standrization value ranges from -3 to 3
np.random.randn(5)

array([ 1.47246609, -0.42966352,  0.68317026, -0.08028995, -1.31763787])

In [183]:
np.random.rand(3, 3)

array([[0.8058902 , 0.61249148, 0.23061803],
       [0.84305079, 0.04670864, 0.90779326],
       [0.22531155, 0.44768864, 0.48191505]])

In [184]:
print(np.random.randint(1, 100, 10))

[39 26 46 28 86 96 59 22 90  5]


In [185]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [186]:
arr.shape

(3, 3)

In [187]:
arr.size

9

In [188]:
arr.ndim

2

In [189]:
arr.dtype

dtype('int64')

In [190]:
print(arr.min(), arr.max(), arr.sum(), arr.mean(), arr.std(), arr.var())

1 9 45 5.0 2.581988897471611 6.666666666666667


In [191]:
print(np.sum(arr, axis=0)) # column wise sum
print(np.sum(arr, axis=1)) # row wise sum

[12 15 18]
[ 6 15 24]


In [192]:
print(np.mean(arr, axis=0)) # column wise min
print(np.mean(arr, axis=1)) # row wise min

[4. 5. 6.]
[2. 5. 8.]


In [193]:
print(arr.mean())
print(arr.mean(axis=0)) # column wise mean
print(arr.mean(axis=1)) # row wise mean

5.0
[4. 5. 6.]
[2. 5. 8.]


In [194]:
print(arr.argmax()) # index of max value
print(arr.argmin()) # index of min value

8
0


In [195]:
arr = np.arange(1,51)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [196]:
arr = arr.reshape(5,10)

In [197]:
print(arr)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [198]:
arr = np.arange(1,31).reshape(5,6)


In [199]:
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [200]:
print(arr[0:,1])

[ 2  8 14 20 26]


In [201]:
print(arr[2:, 4:])

[[17 18]
 [23 24]
 [29 30]]


In [202]:
print("hello")

hello


In [203]:
# boolean indexing

arr = np.arange(1,11)
bool_index = arr % 2 == 0
print(bool_index)

[False  True False  True False  True False  True False  True]


In [204]:
arr = arr[bool_index]
print(arr)

[ 2  4  6  8 10]


In [205]:
# broadcasting
arr = np.arange(10,101,10)
print(arr)
arr *= 10
print(arr)

[ 10  20  30  40  50  60  70  80  90 100]
[ 100  200  300  400  500  600  700  800  900 1000]


In [206]:
# deep and shallow copy
a = np.arange(1,16) # shallow copy - where you can do changes and it will reflect in the original array
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [207]:
slice = a[:7]
print(slice)
slice += 10
print(slice)

[1 2 3 4 5 6 7]
[11 12 13 14 15 16 17]


In [208]:
print(a)

[11 12 13 14 15 16 17  8  9 10 11 12 13 14 15]


In [209]:
# deep copy - where you can do changes and it will not reflect in the original array
b = a.copy()
print(b)

[11 12 13 14 15 16 17  8  9 10 11 12 13 14 15]


In [215]:
# matrix opearation
mat1 = np.array([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]])

mat2 = np.array([[9, 8, 7],
         [6, 5, 4],
         [3, 2, 1]])



In [221]:
mat1 @ mat2 # matrix multiplication
# # or
# np.dot(mat1, mat2) # matrix multiplication

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [222]:
# transpose of a matrix
mat1.T 

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [224]:
# transpose of a matrix
mat2.T

array([[9, 6, 3],
       [8, 5, 2],
       [7, 4, 1]])

In [225]:
# stacking of arrays - we can not stack arrays of different shapes, matrix we can only stack vector or arrays of same shape
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b))) # vertical stacking
print(np.hstack((a,b))) # horizontal stacking
print(np.column_stack((a,b))) # column wise stacking
print(np.row_stack((a,b))) # row wise stacking

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


C:\Users\arthv\AppData\Local\Temp\ipykernel_11556\1902281143.py:8: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((a,b))) # row wise stacking


In [230]:
# splitting of arrays - we can not split arrays of different shapes, matrix we can only split vector or arrays of same shape
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]).reshape(4,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [231]:
np.hsplit(a,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [232]:
np.vsplit(a,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]