In [214]:
import numpy as np


In [215]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [216]:
a = [1,2,3.5]
np.array(a)

array([1. , 2. , 3.5])

In [217]:
lst = [[1,2,3],[4,5,6],[7,8,9]]
np.array(lst)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [218]:
# array generaration
arr = np.arange(1,11,1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [219]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [220]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [221]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [222]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [223]:
# normalizatin value ranges from 0 to 1
np.random.rand(50)

array([0.61871146, 0.76924952, 0.12026713, 0.85777462, 0.77168756,
       0.60798924, 0.77497913, 0.51655138, 0.33202748, 0.60964943,
       0.59117504, 0.36867843, 0.56002873, 0.92983504, 0.03327228,
       0.73664425, 0.15534707, 0.64555302, 0.62090575, 0.72824435,
       0.36978407, 0.01848235, 0.23493151, 0.82383248, 0.52647346,
       0.88848213, 0.69895816, 0.56765989, 0.91117965, 0.57347133,
       0.84742522, 0.59051848, 0.73787376, 0.78115671, 0.83143129,
       0.18259898, 0.34378264, 0.8994217 , 0.92907638, 0.71362823,
       0.83846996, 0.24165807, 0.91153489, 0.63122382, 0.69738708,
       0.47378468, 0.05250683, 0.93680006, 0.31346314, 0.88805945])

In [224]:
# standrization value ranges from -3 to 3
np.random.randn(5)

array([-0.26977521, -0.33052363,  0.03471556,  0.9181739 ,  0.1936336 ])

In [225]:
np.random.rand(3, 3)

array([[0.62050707, 0.5306922 , 0.48082032],
       [0.2882232 , 0.12420444, 0.71562926],
       [0.41781275, 0.10952488, 0.2145404 ]])

In [226]:
print(np.random.randint(1, 100, 10))

[22 52 47 82 78 25 23 84 78 69]


In [227]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [228]:
arr.shape

(3, 3)

In [229]:
arr.size

9

In [230]:
arr.ndim

2

In [231]:
arr.dtype

dtype('int64')

In [232]:
print(arr.min(), arr.max(), arr.sum(), arr.mean(), arr.std(), arr.var())

1 9 45 5.0 2.581988897471611 6.666666666666667


In [233]:
print(np.sum(arr, axis=0)) # column wise sum
print(np.sum(arr, axis=1)) # row wise sum

[12 15 18]
[ 6 15 24]


In [234]:
print(np.mean(arr, axis=0)) # column wise min
print(np.mean(arr, axis=1)) # row wise min

[4. 5. 6.]
[2. 5. 8.]


In [235]:
print(arr.mean())
print(arr.mean(axis=0)) # column wise mean
print(arr.mean(axis=1)) # row wise mean

5.0
[4. 5. 6.]
[2. 5. 8.]


In [236]:
print(arr.argmax()) # index of max value
print(arr.argmin()) # index of min value

8
0


In [237]:
arr = np.arange(1,51)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [238]:
arr = arr.reshape(5,10)

In [239]:
print(arr)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [240]:
arr = np.arange(1,31).reshape(5,6)


In [241]:
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [242]:
print(arr[0:,1])

[ 2  8 14 20 26]


In [243]:
print(arr[2:, 4:])

[[17 18]
 [23 24]
 [29 30]]


In [244]:
print("hello")

hello


In [245]:
# boolean indexing

arr = np.arange(1,11)
bool_index = arr % 2 == 0
print(bool_index)

[False  True False  True False  True False  True False  True]


In [246]:
arr = arr[bool_index]
print(arr)

[ 2  4  6  8 10]


In [247]:
# broadcasting
arr = np.arange(10,101,10)
print(arr)
arr *= 10
print(arr)

[ 10  20  30  40  50  60  70  80  90 100]
[ 100  200  300  400  500  600  700  800  900 1000]


In [248]:
# deep and shallow copy
a = np.arange(1,16) # shallow copy - where you can do changes and it will reflect in the original array
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [249]:
slice_arr = a[:7]
print(slice_arr)
slice_arr += 10
print(slice_arr)

[1 2 3 4 5 6 7]
[11 12 13 14 15 16 17]


In [250]:
print(a)

[11 12 13 14 15 16 17  8  9 10 11 12 13 14 15]


In [251]:
# deep copy - where you can do changes and it will not reflect in the original array
b = a.copy()
print(b)

[11 12 13 14 15 16 17  8  9 10 11 12 13 14 15]


In [252]:
# matrix opearation
mat1 = np.array([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]])

mat2 = np.array([[9, 8, 7],
         [6, 5, 4],
         [3, 2, 1]])



In [253]:
mat1 @ mat2 # matrix multiplication
# # or
# np.dot(mat1, mat2) # matrix multiplication

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [254]:
# transpose of a matrix
mat1.T 

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [255]:
# transpose of a matrix
mat2.T

array([[9, 6, 3],
       [8, 5, 2],
       [7, 4, 1]])

In [256]:
# stacking of arrays - we can not stack arrays of different shapes, matrix we can only stack vector or arrays of same shape
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b))) # vertical stacking
print(np.hstack((a,b))) # horizontal stacking
print(np.column_stack((a,b))) # column wise stacking
print(np.row_stack((a,b))) # row wise stacking

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


C:\Users\arthv\AppData\Local\Temp\ipykernel_19872\1902281143.py:8: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((a,b))) # row wise stacking


In [257]:
# splitting of arrays - we can not split arrays of different shapes, matrix we can only split vector or arrays of same shape
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]).reshape(4,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [258]:
np.hsplit(a,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [259]:
np.vsplit(a,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [260]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [261]:
print(np.sum(s, axis=0)) # column wise sum 
print(np.sum(s, axis=1)) # row wise sum


[45 45 45 45 45 45 45 45 45]
[45 45 45 45 45 45 45 45 45]


In [280]:
b = np.sum(s, axis=0) # for column wise sum
for l in b:
  if l != 45:
    print("Not a valid sudoku for column wise sum")
    break     
else:
  print("Valid sudoku for column wise sum")

Valid sudoku for column wise sum


In [263]:
b = np.sum(s, axis=1) # for row wise sum
for l in b:
  if l != 45:
    print("Not a valid sudoku for row wise sum")
    break     
else:
  print("Valid sudoku for row wise sum")

Valid sudoku for row wise sum


In [264]:
s[0:3, 0:3].sum() # for first 3 rows and first 3 columns


np.int64(45)

In [265]:
for i in range(0, 9, 3):
  for j in range(0, 9, 3):
    print(s[i:i+3, j:j+3].sum()) # for each 3x3 subgrid sum

45
45
45
45
45
45
45
45
45


In [266]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])


In [267]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [268]:
#Find the average age of students.
# data[0:,0].mean()  # Average age is calculated from the first column (index 0)
# or 
np.mean(data[0:,0])  # Using np.mean function

np.float64(18.4)

In [269]:
#Extract Math marks of all students.
data[0:,1]  # Math marks are in the second column (index 1)


array([85, 92, 76, 65, 90])

In [270]:
#Find the highest Science mark.
# data[0:,2].max()  # Science marks are in the third column (index 2)
# or
np.max(data[0:,2])  # Using np.max function

np.int64(95)

In [271]:
#Get details of the student who scored more than 90 in Math.
data[data[0:,1] > 90]

array([[19, 92, 88]])

In [272]:
#Increase Math marks of all students by 5.
data[:, 1] += 5
data  # Display the updated data to verify the changes

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [273]:
#Find how many students are younger than 19.
# data[data[:, 0] < 19].shape[0]
# or
# np.sum(data[:, 0] < 19)
# or
len(data[data[:, 0] < 19])

3

In [274]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[0:,1:], axis=0)  # axis=0 for column-wise mean

array([86.6, 83.2])

In [275]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:, 1] >= 80) & (data[:, 2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [276]:
#Replace all Science marks < 75 with 0.
data[data[:, 2] < 75, 2] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])

In [278]:
data[0:,2:]

array([[78],
       [88],
       [95],
       [ 0],
       [85]])

In [281]:
k = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [282]:
target = np.arange(1, 10)

In [283]:
sorted_columns = np.sort(k, axis=0)


In [284]:
print("Sorted columns:\n", sorted_columns)

Sorted columns:
 [[1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9]]


In [285]:
print(sorted_columns.T)

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


In [286]:
for col in sorted_columns.T:
    print("Column:", col)

Column: [1 2 3 4 5 6 7 8 9]
Column: [1 2 3 4 5 6 7 8 9]
Column: [1 2 3 4 5 6 7 8 9]
Column: [1 2 3 4 5 6 7 8 9]
Column: [1 2 3 4 5 6 7 8 9]
Column: [1 2 3 4 5 6 7 8 9]
Column: [1 2 3 4 5 6 7 8 9]
Column: [1 2 3 4 5 6 7 8 9]
Column: [1 2 3 4 5 6 7 8 9]


In [287]:
np.array_equal(col, target)

True

In [293]:
import numpy as np

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

target = np.arange(1, 10)

sorted_columns = np.sort(s, axis=0) 
for col in sorted_columns.T:        
    if not np.array_equal(col, target):
        print("Not a valid sudoku for column wise verification")
        break
else:
    print("Valid sudoku for column wise verification")


sorted_rows = np.sort(s, axis=1)    
for row in sorted_rows:
    if not np.array_equal(row, target):
        print("Not a valid sudoku for row wise verification")
        break
else:
    print("Valid sudoku for row wise verification")

valid_boxes = True

for i in range(0, 9, 3):
    for j in range(0, 9, 3):

        box = s[i:i+3, j:j+3].flatten()

        if not np.array_equal(np.sort(box), target):
            valid_boxes = False
            break

    if not valid_boxes:
        break

if valid_boxes:
    print("Valid Sudoku Boxes")
else:
    print("Invalid Sudoku Boxes")  


Valid sudoku for column wise verification
Valid sudoku for row wise verification
Valid Sudoku Boxes
