In [2]:
import numpy as np


In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
a = [1,2,3.5]
np.array(a)

array([1. , 2. , 3.5])

In [5]:
lst = [[1,2,3],[4,5,6],[7,8,9]]
np.array(lst)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# array generaration
arr = np.arange(1,11,1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# normalizatin value ranges from 0 to 1
np.random.rand(50)

array([0.51595608, 0.51060011, 0.10559202, 0.49309068, 0.56590464,
       0.06118336, 0.30097764, 0.55193102, 0.97601411, 0.52339895,
       0.85660891, 0.44610298, 0.57194156, 0.03806608, 0.24483426,
       0.26562094, 0.22429147, 0.27587317, 0.19586026, 0.86476953,
       0.30721398, 0.58714711, 0.87696286, 0.79543992, 0.88648842,
       0.03518795, 0.40042986, 0.56473506, 0.19315002, 0.90928338,
       0.72055352, 0.61417708, 0.56065545, 0.01350325, 0.95487113,
       0.04551843, 0.04061674, 0.58868325, 0.75444128, 0.45773886,
       0.80329401, 0.07410592, 0.85010617, 0.97996465, 0.65050252,
       0.03991667, 0.81278624, 0.85751814, 0.86606821, 0.26114325])

In [26]:
# standrization value ranges from -3 to 3
np.random.randn(5)

array([-0.61741298, -1.65513555, -0.05832225,  0.63026733, -0.640188  ])

In [27]:
np.random.rand(3, 3)

array([[0.94373388, 0.22430693, 0.49511542],
       [0.10022067, 0.48600276, 0.43435499],
       [0.59607491, 0.15146829, 0.46025135]])

In [30]:
print(np.random.randint(1, 100, 10))

[98  1 38 35 19 91 81 55 14 49]


In [35]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [36]:
arr.shape

(3, 3)

In [37]:
arr.size

9

In [38]:
arr.ndim

2

In [39]:
arr.dtype

dtype('int64')

In [40]:
print(arr.min(), arr.max(), arr.sum(), arr.mean(), arr.std(), arr.var())

1 9 45 5.0 2.581988897471611 6.666666666666667


In [42]:
print(np.sum(arr, axis=0)) # column wise sum
print(np.sum(arr, axis=1)) # row wise sum

[12 15 18]
[ 6 15 24]


In [44]:
print(np.mean(arr, axis=0)) # column wise min
print(np.mean(arr, axis=1)) # row wise min

[4. 5. 6.]
[2. 5. 8.]


In [50]:
print(arr.mean())
print(arr.mean(axis=0)) # column wise mean
print(arr.mean(axis=1)) # row wise mean

5.0
[4. 5. 6.]
[2. 5. 8.]


In [51]:
print(arr.argmax()) # index of max value
print(arr.argmin()) # index of min value

8
0


In [53]:
arr = np.arange(1,51)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [60]:
arr = arr.reshape(5,10)

In [61]:
print(arr)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [64]:
arr = np.arange(1,31).reshape(5,6)


In [65]:
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [69]:
print(arr[0:,1])

[ 2  8 14 20 26]


In [ ]:
print(arr[2:, 4:])

[[17 18]
 [23 24]
 [29 30]]


In [ ]:
print("hello")