In [ ]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(arr1.shape)

In [29]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(2,3)
print(arr2.size)
print(arr2.ndim)
print(arr2.dtype)
print(arr2.itemsize)


6
1
int64
8


In [23]:
np.arange(0,20,4).reshape(5,1)

array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16]])

In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
one = np.array([1,2,3])
two = np.array([4,5,6])

print(one+two)
print(one-two)
print(one*two)
print(one/two)
print(one**two)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [33]:
three = np.array([1,2,3,4,5,6])

print(np.sqrt(three))
print(np.square(three))
print(np.exp(three))
print(np.sin(three))
print(np.log(three))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[ 1  4  9 16 25 36]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [55]:
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr_2d)  
print(arr_2d[0][2])
print(arr_2d[0,2]) # this is the same as above
print(arr_2d[1:, 1:]) 
print(arr_2d[0:2, 1:])
print(arr_2d[0:2,1:2][1])
arr_2d[0:2,1:2][1] = 69
print(arr_2d[0:2,1:2][1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
3
[[5 6]
 [8 9]]
[[2 3]
 [5 6]]
[5]
[69]


In [56]:
arr = np.array([3, 7, 1, 9, 12, 4, 18, 6, 25, 2, 14, 30, 8, 21, 5, 17, 11, 28, 10, 24])

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

12.75
10.5
8.757139944068497
76.6875


In [67]:
arr = np.array([3, 7, 1, 9, 12, 4, 18, 6, 25, 2, 14, 30, 8, 21, 5, 17, 11, 28, 10, 24])
print(arr[(arr>5) & (arr<20)])
print(arr>5)
arr.sort()
print(arr)

[ 7  9 12 18  6 14  8 17 11 10]
[False  True False  True  True False  True  True  True False  True  True
  True  True False  True  True  True  True  True]
[ 1  2  3  4  5  6  7  8  9 10 11 12 14 17 18 21 24 25 28 30]
